# Generated by Django 5.0.3 on 2024-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
