# Generated by Django 5.0.3 on 2024-03-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumeniki', '0003_alter_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
