# Generated by Django 5.0.3 on 2024-03-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumeniki', '0004_dummypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummypost',
            name='post_date',
            field=models.DateField(),
        ),
    ]
