# Generated by Django 5.0.3 on 2024-03-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumeniki', '0005_alter_dummypost_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummypost',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
